// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: correlatividad.sql

package sqlc

import (
	"context"
)

const addCorrelatividad = `-- name: AddCorrelatividad :exec
INSERT INTO correlatividad_materia (materia_id_materia, id_materia_requerida)
VALUES ($1, $2)
`

type AddCorrelatividadParams struct {
	MateriaIDMateria   int32 `json:"materia_id_materia"`
	IDMateriaRequerida int32 `json:"id_materia_requerida"`
}

func (q *Queries) AddCorrelatividad(ctx context.Context, arg AddCorrelatividadParams) error {
	_, err := q.db.Exec(ctx, addCorrelatividad, arg.MateriaIDMateria, arg.IDMateriaRequerida)
	return err
}

const getCorrelativasDeMateria = `-- name: GetCorrelativasDeMateria :many
SELECT m.id_materia, m.nombre, m.anio, m.cuatrimestre
FROM correlatividad_materia cm
JOIN materia m ON cm.id_materia_requerida = m.id_materia
WHERE cm.materia_id_materia = $1
`

func (q *Queries) GetCorrelativasDeMateria(ctx context.Context, materiaIDMateria int32) ([]Materium, error) {
	rows, err := q.db.Query(ctx, getCorrelativasDeMateria, materiaIDMateria)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Materium
	for rows.Next() {
		var i Materium
		if err := rows.Scan(
			&i.IDMateria,
			&i.Nombre,
			&i.Anio,
			&i.Cuatrimestre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
