// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: materia.sql

package sqlc

import (
	"context"
)

const createMateria = `-- name: CreateMateria :one
INSERT INTO materia (nombre, anio, cuatrimestre)
VALUES ($1, $2, $3)
RETURNING id_materia, nombre, anio, cuatrimestre
`

type CreateMateriaParams struct {
	Nombre       string `json:"nombre"`
	Anio         int32  `json:"anio"`
	Cuatrimestre int32  `json:"cuatrimestre"`
}

func (q *Queries) CreateMateria(ctx context.Context, arg CreateMateriaParams) (Materium, error) {
	row := q.db.QueryRow(ctx, createMateria, arg.Nombre, arg.Anio, arg.Cuatrimestre)
	var i Materium
	err := row.Scan(
		&i.IDMateria,
		&i.Nombre,
		&i.Anio,
		&i.Cuatrimestre,
	)
	return i, err
}

const deleteMateria = `-- name: DeleteMateria :exec
DELETE FROM materia
WHERE id_materia = $1
`

func (q *Queries) DeleteMateria(ctx context.Context, idMateria int32) error {
	_, err := q.db.Exec(ctx, deleteMateria, idMateria)
	return err
}

const getMateriaByID = `-- name: GetMateriaByID :one
SELECT id_materia, nombre, anio, cuatrimestre FROM materia
WHERE id_materia = $1
`

func (q *Queries) GetMateriaByID(ctx context.Context, idMateria int32) (Materium, error) {
	row := q.db.QueryRow(ctx, getMateriaByID, idMateria)
	var i Materium
	err := row.Scan(
		&i.IDMateria,
		&i.Nombre,
		&i.Anio,
		&i.Cuatrimestre,
	)
	return i, err
}

const listMaterias = `-- name: ListMaterias :many
SELECT id_materia, nombre, anio, cuatrimestre FROM materia
ORDER BY anio, cuatrimestre
`

func (q *Queries) ListMaterias(ctx context.Context) ([]Materium, error) {
	rows, err := q.db.Query(ctx, listMaterias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Materium
	for rows.Next() {
		var i Materium
		if err := rows.Scan(
			&i.IDMateria,
			&i.Nombre,
			&i.Anio,
			&i.Cuatrimestre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMateria = `-- name: UpdateMateria :one
UPDATE materia
SET nombre = $2, anio = $3, cuatrimestre = $4
WHERE id_materia = $1
RETURNING id_materia, nombre, anio, cuatrimestre
`

type UpdateMateriaParams struct {
	IDMateria    int32  `json:"id_materia"`
	Nombre       string `json:"nombre"`
	Anio         int32  `json:"anio"`
	Cuatrimestre int32  `json:"cuatrimestre"`
}

func (q *Queries) UpdateMateria(ctx context.Context, arg UpdateMateriaParams) (Materium, error) {
	row := q.db.QueryRow(ctx, updateMateria,
		arg.IDMateria,
		arg.Nombre,
		arg.Anio,
		arg.Cuatrimestre,
	)
	var i Materium
	err := row.Scan(
		&i.IDMateria,
		&i.Nombre,
		&i.Anio,
		&i.Cuatrimestre,
	)
	return i, err
}
