// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CorrelatividadMaterium struct {
	MateriaIDMateria   int32 `json:"materia_id_materia"`
	IDMateriaRequerida int32 `json:"id_materia_requerida"`
}

type Materium struct {
	IDMateria    int32  `json:"id_materia"`
	Nombre       string `json:"nombre"`
	Anio         int32  `json:"anio"`
	Cuatrimestre int32  `json:"cuatrimestre"`
}

type Usuario struct {
	IDUsuario      int32  `json:"id_usuario"`
	NombreApellido string `json:"nombre_apellido"`
	Email          string `json:"email"`
	Telefono       string `json:"telefono"`
}

type UsuarioMaterium struct {
	UsuarioIDUsuario int32         `json:"usuario_id_usuario"`
	MateriaIDMateria int32         `json:"materia_id_materia"`
	Estado           string        `json:"estado"`
	Nota             pgtype.Float4 `json:"nota"`
}
