// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuario.sql

package sqlc

import (
	"context"
)

const createUsuario = `-- name: CreateUsuario :one
INSERT INTO usuario (nombre_apellido, email, telefono)
VALUES ($1, $2, $3)
RETURNING id_usuario, nombre_apellido, email, telefono
`

type CreateUsuarioParams struct {
	NombreApellido string `json:"nombre_apellido"`
	Email          string `json:"email"`
	Telefono       string `json:"telefono"`
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, createUsuario, arg.NombreApellido, arg.Email, arg.Telefono)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.NombreApellido,
		&i.Email,
		&i.Telefono,
	)
	return i, err
}

const deleteUsuario = `-- name: DeleteUsuario :exec
DELETE FROM usuario
WHERE id_usuario = $1
`

func (q *Queries) DeleteUsuario(ctx context.Context, idUsuario int32) error {
	_, err := q.db.Exec(ctx, deleteUsuario, idUsuario)
	return err
}

const getUsuarioByID = `-- name: GetUsuarioByID :one
SELECT id_usuario, nombre_apellido, email, telefono FROM usuario
WHERE id_usuario = $1
`

func (q *Queries) GetUsuarioByID(ctx context.Context, idUsuario int32) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUsuarioByID, idUsuario)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.NombreApellido,
		&i.Email,
		&i.Telefono,
	)
	return i, err
}

const listUsuarios = `-- name: ListUsuarios :many
SELECT id_usuario, nombre_apellido, email, telefono FROM usuario
ORDER BY id_usuario
`

func (q *Queries) ListUsuarios(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.Query(ctx, listUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.IDUsuario,
			&i.NombreApellido,
			&i.Email,
			&i.Telefono,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUsuario = `-- name: UpdateUsuario :one
UPDATE usuario
SET nombre_apellido = $2, email = $3, telefono = $4
WHERE id_usuario = $1
RETURNING id_usuario, nombre_apellido, email, telefono
`

type UpdateUsuarioParams struct {
	IDUsuario      int32  `json:"id_usuario"`
	NombreApellido string `json:"nombre_apellido"`
	Email          string `json:"email"`
	Telefono       string `json:"telefono"`
}

func (q *Queries) UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, updateUsuario,
		arg.IDUsuario,
		arg.NombreApellido,
		arg.Email,
		arg.Telefono,
	)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.NombreApellido,
		&i.Email,
		&i.Telefono,
	)
	return i, err
}
