// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuario_materia.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProgresoUsuario = `-- name: GetProgresoUsuario :many
SELECT m.id_materia, m.nombre, um.estado, um.nota
FROM usuario_materia um
JOIN materia m ON um.materia_id_materia = m.id_materia
WHERE um.usuario_id_usuario = $1
`

type GetProgresoUsuarioRow struct {
	IDMateria int32         `json:"id_materia"`
	Nombre    string        `json:"nombre"`
	Estado    string        `json:"estado"`
	Nota      pgtype.Float4 `json:"nota"`
}

func (q *Queries) GetProgresoUsuario(ctx context.Context, usuarioIDUsuario int32) ([]GetProgresoUsuarioRow, error) {
	rows, err := q.db.Query(ctx, getProgresoUsuario, usuarioIDUsuario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProgresoUsuarioRow
	for rows.Next() {
		var i GetProgresoUsuarioRow
		if err := rows.Scan(
			&i.IDMateria,
			&i.Nombre,
			&i.Estado,
			&i.Nota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEstadoMateria = `-- name: SetEstadoMateria :exec
INSERT INTO usuario_materia (usuario_id_usuario, materia_id_materia, estado, nota)
VALUES ($1, $2, $3, $4)
ON CONFLICT (usuario_id_usuario, materia_id_materia)
DO UPDATE SET estado = EXCLUDED.estado, nota = EXCLUDED.nota
`

type SetEstadoMateriaParams struct {
	UsuarioIDUsuario int32         `json:"usuario_id_usuario"`
	MateriaIDMateria int32         `json:"materia_id_materia"`
	Estado           string        `json:"estado"`
	Nota             pgtype.Float4 `json:"nota"`
}

func (q *Queries) SetEstadoMateria(ctx context.Context, arg SetEstadoMateriaParams) error {
	_, err := q.db.Exec(ctx, setEstadoMateria,
		arg.UsuarioIDUsuario,
		arg.MateriaIDMateria,
		arg.Estado,
		arg.Nota,
	)
	return err
}
